export const SEND_FORM_REQUEST = 'SEND_FORM_REQUEST'
export const SEND_FORM_SUCCESS = 'SEND_FORM_SUCCESS'
export const SEND_FORM_FAILURE = 'SEND_FORM_FAILURE'
export const SET_FORM_PARAM = 'SET_FORM_PARAM'
