import * as actionTypes from './action-types'

const initialState = {
    fields: {
        bankAccountBalance: '',
        bankAccountMonthlyPayment: '',
        bankAccountName: '',
        bankAccountNumber: '',
        carBalance: '',
        carCreditorsPhone: '',
        carLienHolder: '',
        carMonthlyPayment: '',
        creditCard1Balance: '',
        creditCard1Company: '',
        creditCard1CreditorsPhone: '',
        creditCard1MonthlyPayment: '',
        creditCard2Balance: '',
        creditCard2Company: '',
        creditCard2CreditorsPhone: '',
        creditCard2MonthlyPayment: '',
        creditCard3Balance: '',
        creditCard3Company: '',
        creditCard3CreditorsPhone: '',
        creditCard3MonthlyPayment: '',
        email: '',
        emergency1Address: '',
        emergency1CityStateZip: '',
        emergency1Name: '',
        emergency1Phone1: '',
        emergency1Phone2: '',
        emergency1Relation: '',
        emergency2Address: '',
        emergency2CityStateZip: '',
        emergency2Name: '',
        emergency2Phone1: '',
        emergency2Phone2: '',
        emergency2Relation: '',
        employment1Address: '',
        employment1CityStateZip: '',
        employment1Employer: '',
        employment1Occupation: '',
        employment1Phone: '',
        employment1Supervisor: '',
        employment1WeeklyHours: '',
        employment1Years: '',
        employment2Address: '',
        employment2CityStateZip: '',
        employment2Employer: '',
        employment2Occupation: '',
        employment2Phone: '',
        employment2Supervisor: '',
        employment2WeeklyHours: '',
        employment2Years: '',
        finalConfirmation: '',
        firstName: '',
        income1Amount: '',
        income1Period: '',
        income1Proof: '',
        income1Source: '',
        income2Amount: '',
        income2Period: '',
        income2Proof: '',
        income2Source: '',
        income3Amount: '',
        income3Period: '',
        income3Proof: '',
        income3Source: '',
        lastName: '',
        middleName: '',
        nextPreviousAddress: '',
        nextPreviousCityStateZip: '',
        nextPreviousLandlord: '',
        nextPreviousLandlordPhone: '',
        nextPreviousLength: '',
        nextPreviousReason: '',
        nextPreviousRent: '',
        nextPreviousRentUpToDate: '',
        occupant1Age: '',
        occupant1Name: '',
        occupant1Occupation: '',
        occupant1Relationship: '',
        occupant2Age: '',
        occupant2Name: '',
        occupant2Occupation: '',
        occupant2Relationship: '',
        occupant3Age: '',
        occupant3Name: '',
        occupant3Occupation: '',
        occupant3Relationship: '',
        occupant4Age: '',
        occupant4Name: '',
        occupant4Occupation: '',
        occupant4Relationship: '',
        otherCredit: '',
        otherCreditBalance: '',
        otherCreditCreditorsPhone: '',
        otherCreditMonthlyPayment: '',
        phone: '',
        phoneAlt: '',
        presentAddress: '',
        presentCityStateZip: '',
        presentLandlord: '',
        presentLandlordPhone: '',
        presentLength: '',
        presentReason: '',
        presentRent: '',
        presentRentUpToDate: '',
        previousAddress: '',
        previousCityStateZip: '',
        previousLandlord: '',
        previousLandlordPhone: '',
        previousLength: '',
        previousReason: '',
        previousRent: '',
        previousRentUpToDate: '',
        questionBeenBankrupt: '',
        questionBeenSued: '',
        questionBrokenLease: '',
        questionBroughtToCourt: '',
        questionFelony: '',
        questionLockedOutSheriff: '',
        questionMoveInAmountAvailable: '',
        questionMovedOwingMoney: '',
        reference1Address: '',
        reference1CityStateZip: '',
        reference1Name: '',
        reference1Phone1: '',
        reference1Phone2: '',
        reference1Relation: '',
        reference2Address: '',
        reference2CityStateZip: '',
        reference2Name: '',
        reference2Phone1: '',
        reference2Phone2: '',
        reference2Relation: '',
        vehicle1Color: '',
        vehicle1Make: '',
        vehicle1Model: '',
        vehicle1Plate: '',
        vehicle1State: '',
        vehicle1Year: '',
        vehicle2Color: '',
        vehicle2Make: '',
        vehicle2Model: '',
        vehicle2Plate: '',
        vehicle2State: '',
        vehicle2Year: '',
        vehicle3Color: '',
        vehicle3Make: '',
        vehicle3Model: '',
        vehicle3Plate: '',
        vehicle3State: '',
        vehicle3Year: '',
    },
    send: {
        success: false,
        doing: false,
        errors: [],
        paramErrors: {},
    },
}

const actionsMap = {
    [actionTypes.SET_FORM_PARAM]: (state, action) => {
        return {
            ...state,
            fields: {
                ...state.fields,
                [action.name]: action.value,
            },
            send: {
                ...state.send,
            },
        }
    },

    [actionTypes.SEND_FORM_REQUEST]: (state, action) => {
        return {
            ...state,
            send: {
                ...state.send,
                doing: true,
                errors: [],
                paramErrors: {},
            },
        }
    },

    [actionTypes.SEND_FORM_SUCCESS]: (state, action) => {
        return {
            ...initialState,
            send: {
                ...initialState.send,
                success: true,
            },
        }
    },

    [actionTypes.SEND_FORM_FAILURE]: (state, action) => {
        return {
            ...state,
            send: {
                ...state.send,
                doing: false,
                errors: action.errors,
                paramErrors: action.paramErrors,
            },
        }
    },
}

export default function(state = initialState, action = {}) {
    const fn = actionsMap[action.type]
    return fn ? fn(state, action) : state
}
